<?php

namespace MultiMaps;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-26 at 07:57:33.
 */
class YandexTest extends \PHPUnit\Framework\TestCase {

	/**
	 * @var Yandex
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp(): void {
		global $egMultiMaps_AllowGeocoderTests;
		if ( !$egMultiMaps_AllowGeocoderTests ) {
			$this->markTestSkipped( 'Requires $egMultiMaps_AllowGeocoderTests' );
		}
		$this->object = new Yandex;
		parent::setUp();
	}

	/**
	 * @covers MultiMaps\BaseMapService::getMapData
	 */
	public function testParseGeocoderMarker() {
		$this->assertMatchesRegularExpression(
			'{"markers":[{"pos":[{"lat":[0-9\.]+,"lon":[0-9\.]+}]}],"bounds":{"ne":{"lat":[0-9\.]+,"lon":[0-9\.]+},"sw":{"lat":[0-9\.]+,"lon":[0-9\.]+}}}',
			\FormatJson::encode( $this->object->getMapData( [ 'Moscow', 'service=yandex' ] ) )
		);
	}

	/**
	 * @covers MultiMaps\BaseMapService::getMapData
	 */
	public function testParseGeocoderRectangle() {
		$this->assertMatchesRegularExpression(
			'{"rectangles":\[{"pos":\[{"lat":[0-9\.]+,"lon":[0-9\.]+},{"lat":[0-9\.]+,"lon":[0-9\.]+}\]}\],"bounds":{"ne":{"lat":[0-9\.]+,"lon":[0-9\.]+},"sw":{"lat":[0-9\.]+,"lon":[0-9\.]+}}}',
			\FormatJson::encode( $this->object->getMapData( [ 'rectangle=Moscow', 'service=yandex' ] ) )
		);
	}

	/**
	 * @covers MultiMaps\BaseMapService::getMapData
	 */
	public function testParseGeocoderRectangles() {
		$this->assertMatchesRegularExpression(
			'/\{"rectangles":\[\{"pos":\[\{"lat":[-0-9\.]+,"lon":[-0-9\.]+\},\{"lat":[-0-9\.]+,"lon":[-0-9\.]+\}\]\},\{"pos":\[\{"lat":[-0-9\.]+,"lon":[-0-9\.]+\},\{"lat":[-0-9\.]+,"lon":[-0-9\.]+\}\]\}\],"bounds":\{"ne":\{"lat":[-0-9\.]+,"lon":[-0-9\.]+\},"sw":\{"lat":[-0-9\.]+,"lon":[-0-9\.]+\}\}\}/',
			\FormatJson::encode( $this->object->getMapData( [ 'rectangle=Moscow;London', 'service=yandex' ] ) )
		);
	}

	/**
	 * @covers MultiMaps\BaseMapService::getMapData
	 */
	public function testParseGeocoderCircle() {
		$this->assertMatchesRegularExpression(
			'{"circles":\[{"radius":\[[0-9\.]+\],"pos":\[{"lat":[0-9\.]+,"lon":[0-9\.]+}\]}\],"bounds":{"ne":{"lat":[0-9\.]+,"lon":[0-9\.]+},"sw":{"lat":[0-9\.]+,"lon":[0-9\.]+}}}',
			\FormatJson::encode( $this->object->getMapData( [ 'circle=Moscow', 'service=yandex' ] ) )
		);
	}

}
